import { initEditState, initProject, initProjectState, initUserState } from 'src/store/constants';

export const ProjectContext = {
  state: initProjectState,
  info: initUserState,
  projects: [],
  setProjects: () => {},
  loading: false,
  setLoading: () => {},
  setInfo: () => {},
  editId: 0,
  editInfo: initEditState,
  setEditInfo: () => {},
  projectStatus: '',
  setProjectStatus: () => {},
  query: '',
  setQuery: () => {},
  viewTask: [],
  setViewTask: () => {},
  viewTeam: [],
  setViewTeam: () => {},
  users: [],
  setUsers: () => {},
  tasks: [],
  setTasks: () => {},
  setEditId: () => {},
  getProject: () => {},
  getProjectInfo: () => {},
  setProject: () => {},
  saveTask: () => {},
  quantity: [],
  setQuantity: () => {},
  getMemberProject: () => {},
  getTasks: () => {},
  projectInfo: initProject,
  setProjectInfo: () => {},
  getProjectAll: () => {},
  getQuantityProjects: () => {},
  isChange: false,
  setIsChange: () => {},
  customer: [],
  getCustomer: () => {},
  startDate: '',
  setStartDate: () => {},
  endDate: '',
  setEndDate: () => {},
  title: '',
  setTitle: () => {},
  activeProject: () => {},
  inactiveProject: () => {},
  deleteTask: () => {},
  getEditTask: () => {},
  getTimeSheetTasks: () => {},
  getTimeSheetTeams: () => {}
};
